
services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
      # Only will build development stage from our dockerfile
      target: development
    env_file:
        - .env
    volumes:
      - .:/usr/src/app
    # Run in dev Mode: npm run start:dev
    command: npm run start:dev
    ports:
      - 3000:3000
    depends_on:
      - redis
      - postgres
    container_name: 'seuinvest-back'
    networks:
      - seu-investimento


  redis: # Name of container
    image: redis:6.0.16
    ports:
      - 6379:6379
    volumes: 
      - redis:/data
    container_name: 'redis'
    networks:
      - seu-investimento

  postgres:
    image: postgres:16.1
    restart: always
    ports: 
      - '5432:5432'
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    container_name: 'pgsql'
    volumes:
      - docker-nest-postgres:/var/lib/postgresql/data
       - ./scripts/:/docker-entrypoint-initdb.d/
    networks:
      - seu-investimento

 
volumes:
  docker-nest-postgres:
  redis:
    driver: local

networks:
  seu-investimento:
    driver: bridge